version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_USER=default
      - REDIS_PASSWORD=default
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=default
      - RABBITMQ_DEFAULT_PASS=default
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  scylladb:
    image: scylladb/scylla:latest
    ports:
      - "9042:9042"
    volumes:
      - scylladb-data:/var/lib/scylla
      - ./src/configs/scylladb/config.yml:/etc/scylla/scylla.yaml

volumes:
  redis-data:
  rabbitmq-data:
  scylladb-data:
